version: '3.7'
services:
    s3:
        image: minio/minio:RELEASE.2020-03-25T07-03-04Z
        environment:
            MINIO_ACCESS_KEY: admin
            MINIO_SECRET_KEY: password
        ports:
        - "9000:9000"
        volumes:
            - ./volumes/minio/:/data
        entrypoint: sh
        command: >
            -c 'mkdir -p /data/bucket1
            && /usr/bin/minio server /data'

    restic:
        image: lobaro/restic-backup-docker:1.2-0.9.4
        environment:
            AWS_ACCESS_KEY_ID: "admin"
            AWS_SECRET_ACCESS_KEY: "password"
            RESTIC_REPOSITORY: "s3:http://s3:9000/bucket1"
            RESTIC_PASSWORD: secret
        volumes:
            - ./data/:/data/